name: Scala CI

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Download datasets
        run: mkdir -p ~/work/SynapseML/SynapseML/target/scala-2.12/datasets && wget https://mmlspark.blob.core.windows.net/installers/datasets-2021-07-27.tgz && tar -xzvf datasets-2021-07-27.tgz

      - name: Run tests
        run: sbt "project lightgbm" test
